#!/usr/bin/env bash

#This script is the same as running `transmission-remote` if you have it installed locally.
# Run ./transmission-remote-docker -h   to see. 
 
docker exec -it `./get_container_id_of_transmission.sh` transmission-remote $@
